# -*- coding: utf-8 -*-
"""Pokemon Comments API.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1KKs_y8a8JuKqVmVlmdl1ODYM-jiSdwnh

#**API**
"""

# install library
!pip install google-api-python-client

from googleapiclient.discovery import build
import pandas as pd

# My Google API Key
API_KEY = "xxxxxxxxxxxxxxxxxxxxxxx"

# Pokémon Presents video ID
VIDEO_ID = "Dh2WcRJOVPU"

# Build YouTube API connection
youtube = build("youtube", "v3", developerKey=API_KEY)

# print 5 comments
for item in response["items"][:5]:
    comment = item["snippet"]["topLevelComment"]["snippet"]["textDisplay"]
    print(comment)
    print("---")

import time
from googleapiclient.discovery import build
import pandas as pd

# Define function to get top-level comments from a YouTube video
def get_comments_with_id(video_id, api_key, max_comments=2000):
    youtube = build("youtube", "v3", developerKey=api_key)

    comments = []
    next_page_token = None

    # Request up to 100 comment per page, ordered by relevance
    while len(comments) < max_comments:
        request = youtube.commentThreads().list(
            part="snippet",
            videoId=video_id,
            maxResults=100,
            order="relevance",
            pageToken=next_page_token
        )
        response = request.execute()

        for item in response["items"]:
            snippet = item["snippet"]["topLevelComment"]["snippet"]
            comments.append({
                "comment_id": item["snippet"]["topLevelComment"]["id"],
                "text": snippet["textDisplay"],
                "author": snippet["authorDisplayName"],
                "likes": snippet["likeCount"],
                "published_at": snippet["publishedAt"],
                "type": "top_level"
            })

        # exit loop if no further pages
        next_page_token = response.get("nextPageToken")

        if not next_page_token:
            break

        # Pause between requests to avoid hitting API rate limits
        time.sleep(0.5)
        print(f"has captured {len(comments)} comments...")

    return comments


top_comments = get_comments_with_id(VIDEO_ID, API_KEY)
df_top = pd.DataFrame(top_comments)
print(f"Total comments：{len(df_top)}")

# Define function to get replies for a given top-level comment using parent comment ID
def get_replies(api_key, parent_id):
    youtube = build("youtube", "v3", developerKey=api_key)
    replies = []

    try:
        request = youtube.comments().list(
            part="snippet",
            parentId=parent_id,
            maxResults=100
        )
        response = request.execute()

        # Extract relevant fields from each reply
        for item in response["items"]:
            snippet = item["snippet"]
            replies.append({
                "comment_id": item["id"],
                "text": snippet["textDisplay"],
                "author": snippet["authorDisplayName"],
                "likes": snippet["likeCount"],
                "published_at": snippet["publishedAt"],
                "type": "reply"
            })
    except Exception as e:
        print(f"Error: {e}")

    return replies

# Sort top-level comments by like count and select top 100 for reply collection
df_top_sorted = df_top.sort_values("likes", ascending=False).head(100)

# Iterate through top 100 comments and get their replies with rate limiting
all_replies = []
for i, (idx, row) in enumerate(df_top_sorted.iterrows()):
    replies = get_replies(API_KEY, row["comment_id"])
    all_replies.extend(replies)
    time.sleep(0.5)

    if (i+1) % 10 == 0:
        print(f" {i+1}/100 replies，has captured {len(all_replies)} replies...")

print(f"Total replies：{len(all_replies)}")

# Merge top-level comments and replies
df_replies = pd.DataFrame(all_replies)
df_all = pd.concat([df_top, df_replies], ignore_index=True)
print(f"Total comments (top-level + replies): {len(df_all)}")
print(f"- Top-level comments: {len(df_top)}")
print(f"- Replies: {len(df_replies)}")

# Preview the data
print(df_all.head())
print(df_all.info())

# Save to CSV
df_all.to_csv("pokemon_comments.csv", index=False)
print("Data saved to pokemon_comments.csv")

#Data Preprocessing

import re
import html

def clean_text(text):
    # Decode HTML entities (e.g. &#39; → ')
    text = html.unescape(text)

    # Remove URLs
    text = re.sub(r'http\S+|www\S+', '', text)

    # Remove HTML tags (e.g. <br>, <b>)
    text = re.sub(r'<[^>]+>', '', text)

    # Remove emojis and special characters
    text = re.sub(r'[^\x00-\x7F]+', '', text)

    # Remove extra whitespace
    text = re.sub(r'\s+', ' ', text).strip()

    return text

# Apply cleaning
df_all["cleaned_text"] = df_all["text"].apply(clean_text)

# Remove non-English comments (keep only comments with mostly ASCII characters)
df_all = df_all[df_all["cleaned_text"].str.len() > 0]

# Remove comments that are too short (less than 3 words)
df_all = df_all[df_all["cleaned_text"].apply(lambda x: len(x.split()) >= 3)]

# Remove duplicates
df_all = df_all.drop_duplicates(subset="cleaned_text")

# Summary
print(f"Comments after cleaning: {len(df_all)}")
print(f"Comments removed: {3118 - len(df_all)}")
print("\nSample cleaned comments:")
for text in df_all["cleaned_text"].head(5):
    print(f"- {text}")

# Save cleaned data
df_all.to_csv("pokemon_comments_cleaned.csv", index=False)
print("\nCleaned data saved to pokemon_comments_cleaned.csv")

df = pd.read_csv("pokemon_comments_cleaned.csv")
print(f"Total rows: {len(df)}")
print(f"Columns: {df.columns.tolist()}")
df.head(10)

# Download CSV.
from google.colab import files
df.to_csv("pokemon_comments_cleaned.csv", index=False)
files.download("pokemon_comments_cleaned.csv")

"""#**LDA Modeling**"""

# install library

!pip install -q pandas gensim pyLDAvis nltk matplotlib seaborn wordcloud

import warnings
warnings.filterwarnings("ignore")

import pandas as pd
import numpy as np
import gensim
import gensim.corpora as corpora
from gensim.models import LdaModel
from gensim.models.coherencemodel import CoherenceModel
import pyLDAvis
import pyLDAvis.gensim_models
from nltk.tokenize import word_tokenize
from nltk.corpus import stopwords
import nltk
import matplotlib.pyplot as plt
import seaborn as sns
from wordcloud import WordCloud

nltk.download('punkt', quiet=True)
nltk.download('stopwords', quiet=True)
nltk.download('wordnet', quiet=True)
nltk.download('punkt_tab', quiet=True)

"""### Data Preprocessing: Define stopwords, Tokenization"""

# Load data
df = pd.read_csv("pokemon_comments_cleaned.csv")
print(f"Loaded: {len(df)} comments")

# Define stopwords
nltk_stopwords = set(stopwords.words('english'))
custom_stopwords = {
    # Too generic for Pokemon discussion
    'pokemon', 'game', 'games', 'year', 'years', 'time', 'back', 'know',
    'think', 'like', 'get', 'one', 'good', 'great', 'love',
    # Colloquial/meaningless
    'lol', 'yeah', 'bro', 'thats', 'dont', 'cant','would', 'could','lmao',
    'literally', 'actually', 'really', 'though', 'maybe','please', 'also',
    'probably', 'definitely', 'honestly', 'basically','finally','might','hopefully',
    # Generic verbs
    'make', 'made', 'want', 'see', 'come', 'give', 'looked','came','agree'
    'take', 'took', 'feel', 'felt', 'said', 'say', 'went', 'makes','play',
    'watch', 'hate', 'played', 'mean', 'means','believe','called','sorry',
    'going', 'getting', 'putting', 'taking', 'saying', 'tell','turning',
    'making', 'looking', 'hoping', 'playing', 'thinking','bring','stop',
    # Generic adjectives
    'good', 'great', 'cool', 'awesome', 'better',
    'best', 'bad', 'new', 'old', 'big', 'little', 'pretty',
    'sure', 'real', 'able', 'similar', 'almost', 'glad',
    # Generic nouns
    'thing', 'things', 'something', 'nothing', 'everything', 'anything','cloud',
    'someone', 'everyone', 'people', 'way', 'day', 'today', 'hope', 'need', 'starters',
    'prop', 'thought', 'looks', 'make', 'wind', 'wave', 'others', 'legs','animal',
    # Filler words
    'also', 'even', 'still', 'already', 'ever', 'never','instead',
    'always', 'every', 'another', 'around', 'away', 'back','thank', 'okay',
    'else', 'next', 'since', 'though', 'either', 'much', 'first',
    'many', 'well', 'right', 'long', 'wait', 'let', 'keep','comes',
    # Misspellings
    'pokmon', 'theyre','pombon', 'gon',
    # Person names (noise)
    'chris', 'brown',
}
final_stopwords = nltk_stopwords.union(custom_stopwords)

# Tokenization function (following lecture style)
def tokenize_text(text):
    words = word_tokenize(str(text))
    return [word.lower() for word in words
            if word.isalnum()
            and word.lower() not in final_stopwords
            and len(word) > 3]

# Apply tokenization
print("Tokenizing comments...")
df['tokens'] = df['cleaned_text'].apply(tokenize_text)

# Remove empty token lists
df = df[df['tokens'].map(len) > 0].reset_index(drop=True)

# Save tokens
df['tokens_str'] = df['tokens'].apply(lambda x: ','.join(x))
df.to_csv("pokemon_comments_cleaned.csv", index=False)

print(f"Comments after tokenization: {len(df)}")
print(f"\nSample tokens:")
for i, row in df.head(3).iterrows():
    print(f"- {row['tokens']}")

"""Cell 3：建立語料庫"""

# Build dictionary and corpus (following lecture style)
dictionary = corpora.Dictionary(df['tokens'])

# Filter extremes
dictionary.filter_extremes(no_below=5, no_above=0.5)

# Build corpus
corpus = [dictionary.doc2bow(text) for text in df['tokens']]

print(f"Dictionary size (unique words): {len(dictionary)}")
print(f"Corpus size (number of comments): {len(corpus)}")

"""Cell 4：訓練LDA模型"""

# Train LDA model
lda_model = gensim.models.LdaModel(
    corpus=corpus,
    id2word=dictionary,
    num_topics=4,
    random_state=42,
    passes=15,
    iterations=500,
    alpha='auto',
    eta='auto',
    minimum_probability=0.01
)

# Output LDA topics with top 10 keywords
print("=== LDA Topics ===")
for topic_id, words in lda_model.show_topics(num_topics=4, num_words=10, formatted=False):
    print(f"\nTopic {topic_id + 1}: {[word for word, _ in words]}")

"""Cell 5: 評估模型品質"""

from gensim.models.coherencemodel import CoherenceModel

# ==============================
# Coherence Score
# ==============================
coherence_model_lda = CoherenceModel(
    model=lda_model,
    texts=df['tokens'].tolist(),
    dictionary=dictionary,
    coherence='c_v'
)
coherence_lda = coherence_model_lda.get_coherence()
print(f"LDA Coherence Score: {coherence_lda:.3f}")

# ==============================
# Topic Diversity Score
# ==============================
def calculate_lda_topic_diversity(lda_model, top_n_words=10):
    topics = lda_model.show_topics(
        num_topics=lda_model.num_topics,
        num_words=top_n_words,
        formatted=False
    )
    unique_words = set()
    for topic in topics:
        unique_words.update([word for word, _ in topic[1]])
    return len(unique_words) / (top_n_words * lda_model.num_topics)

lda_topic_diversity = calculate_lda_topic_diversity(lda_model)
print(f"LDA Topic Diversity Score: {lda_topic_diversity:.3f}")

"""進行pyLDAvis視覺化"""

import pyLDAvis
import pyLDAvis.gensim_models
import pickle

# Save model immediately
lda_model.save("lda_model_best")
with open("corpus_best.pkl", "wb") as f:
    pickle.dump(corpus, f)
dictionary.save("dictionary_best")
print("Model saved!")

# pyLDAvis visualization
pyLDAvis.enable_notebook()
vis = pyLDAvis.gensim_models.prepare(
    lda_model,
    corpus,
    dictionary,
    sort_topics=False
)

pyLDAvis.save_html(vis, 'lda_visualization.html')
print("pyLDAvis saved!")

vis

import matplotlib.pyplot as plt
import numpy as np

feature_names = list(dictionary.token2id.keys())
topic_labels = [
    "Topic 1: Nintendo & Brand Reaction",
    "Topic 2: New Generation Games on Switch",
    "Topic 3: Anniversary Celebrations & Starter Design",
    "Topic 4: Extended Game Announcements"
]
colors = ['steelblue', 'coral', 'mediumseagreen', 'mediumpurple']

# ── Figure 1: Top 10 keywords per topic ──
fig, axes = plt.subplots(2, 2, figsize=(16, 12))
axes = axes.flatten()

for topic_idx in range(4):
    topic_words = lda_model.show_topic(topic_idx, topn=10)
    words = [w for w, _ in topic_words]
    weights = [v for _, v in topic_words]

    axes[topic_idx].barh(words[::-1], weights[::-1], color=colors[topic_idx])
    axes[topic_idx].set_title(topic_labels[topic_idx], fontsize=12,
                               fontweight='bold', pad=10)
    axes[topic_idx].set_xlabel("Word Probability", fontsize=10)
    axes[topic_idx].spines['top'].set_visible(False)
    axes[topic_idx].spines['right'].set_visible(False)

plt.suptitle("LDA Topic Modeling: Top Keywords per Topic\n(Pokémon 30th Anniversary YouTube Comments)",
             fontsize=14, fontweight='bold')
plt.tight_layout()
plt.savefig("lda_keywords.png", dpi=150, bbox_inches='tight')
plt.show()
print("Figure 1 saved!")

# ── Figure 2: Topic distribution pie chart ──
topic_assignments = [max(lda_model.get_document_topics(doc), key=lambda x: x[1])[0]
                     for doc in corpus]
topic_counts = np.bincount(topic_assignments, minlength=4)

short_labels = [
    "Topic 1: Nintendo & Brand Reaction",
    "Topic 2: New Generation Games on Switch",
    "Topic 3: Anniversary Celebrations & Starter Design",
    "Topic 4: Extended Game Announcements",
]

fig, ax = plt.subplots(figsize=(10, 8))
wedges, texts, autotexts = ax.pie(
    topic_counts,
    labels=short_labels,
    autopct='%1.1f%%',
    colors=colors,
    startangle=90,
    pctdistance=0.85
)
for text in texts:
    text.set_fontsize(11)
for autotext in autotexts:
    autotext.set_fontsize(11)
    autotext.set_fontweight('bold')

ax.set_title("Topic Distribution in YouTube Comments\n(Pokémon 30th Anniversary)",
             fontsize=14, fontweight='bold', pad=20)
plt.tight_layout()
plt.savefig("lda_distribution.png", dpi=150, bbox_inches='tight')
plt.show()
print("Figure 2 saved!")