# -*- coding: utf-8 -*-
"""Pokemon_Comments_Sentiment_Analysis.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1TUDcoZMV3CPXTWkpm5CQAY9zIJAHwUqd

# **Sentiment Analysis**
"""

#Install library
!pip install transformers torch scipy vaderSentiment -q

import torch
from transformers import AutoTokenizer, AutoModelForSequenceClassification
from scipy.special import softmax
from vaderSentiment.vaderSentiment import SentimentIntensityAnalyzer
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import os
os.environ["HF_HUB_DISABLE_SYMLINKS_WARNING"] = "1"

# Load data
df = pd.read_csv("pokemon_comments_cleaned.csv")
print(f"Loaded: {len(df)} comments")
print(f"Columns: {df.columns.tolist()}")
print(f"\nSample cleaned_text:")
for text in df['cleaned_text'].head(3):
    print(f"- {text[:80]}...")

"""### Load the Model of VADER"""

from vaderSentiment.vaderSentiment import SentimentIntensityAnalyzer

# VADER is a lexicon-based sentiment model designed for social media text.
# It requires no training and works by looking up words in a pre-built dictionary.
# We define get_vader_sentiment() to:
# - Take a comment as input
# - Return a compound score between -1 and +1
# - Classify as Positive (>=0.05), Negative (<=-0.05), or Neutral (in between)
# These thresholds are the standard recommended values from the original VADER paper.

analyzer = SentimentIntensityAnalyzer()

def get_vader_sentiment(text):
    scores = analyzer.polarity_scores(str(text))
    compound = scores['compound']
    if compound >= 0.05:
        label = 'Positive'
    elif compound <= -0.05:
        label = 'Negative'
    else:
        label = 'Neutral'
    return pd.Series({
        'vader_sentiment': label,
        'vader_compound': compound
    })

print("VADER loaded and get_vader_sentiment() defined.")

"""### Load the Model of RoBERTa"""

from transformers import AutoTokenizer, AutoModelForSequenceClassification
from scipy.special import softmax
import torch
import numpy as np

# RoBERTa is a transformer-based deep learning model.
# We use the cardiffnlp/twitter-roberta-base-sentiment version,
# which was fine-tuned specifically on Twitter data — making it
# well-suited for informal social media language like YouTube comments.
# We define get_roberta_sentiment() to:
# - Tokenize the input text (convert words to numbers the model understands)
# - Run the model to get raw logits (unnormalised scores for each class)
# - Apply softmax to convert logits into probabilities
# - Return the class with the highest probability: Negative / Neutral / Positive
# max_length=512 is set because RoBERTa has a token limit.
# torch.no_grad() disables gradient computation to save memory during inference.
# A try/except is included to handle any comments that cause errors,
# defaulting them to Neutral to avoid breaking the analysis.

model_name = "cardiffnlp/twitter-roberta-base-sentiment"
rb_tokenizer = AutoTokenizer.from_pretrained(model_name)
rb_model = AutoModelForSequenceClassification.from_pretrained(model_name)

def get_roberta_sentiment(text):
    try:
        tokens = rb_tokenizer(str(text), truncation=True, padding=True,
                              max_length=512, return_tensors="pt")
        with torch.no_grad():
            logits = rb_model(**tokens).logits
        scores = softmax(logits.numpy()[0])
        label = ['Negative', 'Neutral', 'Positive'][np.argmax(scores)]
        return pd.Series({
            'roberta_sentiment': label,
            'roberta_negative': round(float(scores[0]), 4),
            'roberta_neutral': round(float(scores[1]), 4),
            'roberta_positive': round(float(scores[2]), 4)
        })
    except:
        return pd.Series({
            'roberta_sentiment': 'Neutral',
            'roberta_negative': 0.0,
            'roberta_neutral': 1.0,
            'roberta_positive': 0.0
        })

print("RoBERTa loaded and get_roberta_sentiment() defined.")

"""## Manually Mark 100 Comments"""

import pandas as pd
import numpy as np

df = pd.read_csv("pokemon_comments_cleaned.csv")

# Randomly sample 100 comments with fixed seed for reproducibility
sample = df[['cleaned_text']].sample(n=100, random_state=42).reset_index(drop=True)

# Add empty column for manual labelling
sample['manual_label'] = ''

# Save to CSV
sample.to_csv("manual_labelling.csv", index=False)
print("Saved 100 comments to manual_labelling.csv")
print(sample.head())

# Download CSV
from google.colab import files
files.download("manual_labelling.csv")

# Upload CSV
from google.colab import files
uploaded = files.upload()

import pandas as pd

# Read the manually labelled data
df_manual = pd.read_csv("manual_labelling_done.csv")
print(f"Total rows: {len(df_manual)}")
print(f"Columns: {df_manual.columns.tolist()}")
print(f"\nLabel distribution:")
print(df_manual['manual_label'].value_counts())
print(f"\nAny empty labels: {df_manual['manual_label'].isna().sum()}")
print(df_manual.head(3))

from sklearn.metrics import accuracy_score, classification_report
import pandas as pd

df_manual = pd.read_csv("manual_labelling_done.csv")
y_true = df_manual['manual_label']
X_test = df_manual['cleaned_text']

# VADER — use the function defined in Cell A1
y_pred_vader = X_test.apply(
    lambda x: get_vader_sentiment(x)['vader_sentiment']
)
acc_vader = accuracy_score(y_true, y_pred_vader)
print("=== VADER ===")
print(f"Accuracy: {acc_vader:.4f}")
print(classification_report(y_true, y_pred_vader))

# RoBERTa — use the function defined in Cell A2
y_pred_roberta = X_test.apply(
    lambda x: get_roberta_sentiment(x)['roberta_sentiment']
)
acc_roberta = accuracy_score(y_true, y_pred_roberta)
print("=== RoBERTa ===")
print(f"Accuracy: {acc_roberta:.4f}")
print(classification_report(y_true, y_pred_roberta))

# Summary
print("=== Summary ===")
print(f"VADER Accuracy:   {acc_vader:.4f}")
print(f"RoBERTa Accuracy: {acc_roberta:.4f}")
if acc_roberta > acc_vader:
    print("\nRoBERTa performs better → use RoBERTa for final analysis")
else:
    print("\nVADER performs better → use VADER for final analysis")

"""## Draw Confusion Matrix to Compare Two Models"""

from sklearn.metrics import confusion_matrix, ConfusionMatrixDisplay
import matplotlib.pyplot as plt
import pandas as pd

# Load manually labelled dataset as test set
df_manual = pd.read_csv("manual_labelling_done.csv")

y_true = df_manual['manual_label']
X_test = df_manual['cleaned_text']
labels = ['Negative', 'Neutral', 'Positive']

print(f"Test set: {len(y_true)} comments")
print(y_true.value_counts())

# VADER Confusion Matrix

y_pred_vader = X_test.apply(
    lambda x: get_vader_sentiment(x)['vader_sentiment']
)

cm_vader = confusion_matrix(y_true, y_pred_vader, labels=labels)
disp = ConfusionMatrixDisplay(confusion_matrix=cm_vader, display_labels=labels)

fig, ax = plt.subplots(figsize=(8, 6))
disp.plot(ax=ax, colorbar=True, cmap='Blues')
ax.set_title('Confusion Matrix - VADER (Accuracy: 52%)',
             fontsize=12, fontweight='bold')
plt.tight_layout()
plt.savefig("cm_vader.png", dpi=150, bbox_inches='tight')
plt.show()

# RoBERTa Confusion Matrix

y_pred_roberta = X_test.apply(
    lambda x: get_roberta_sentiment(x)['roberta_sentiment']
)

cm_roberta = confusion_matrix(y_true, y_pred_roberta, labels=labels)
disp = ConfusionMatrixDisplay(confusion_matrix=cm_roberta, display_labels=labels)

fig, ax = plt.subplots(figsize=(8, 6))
disp.plot(ax=ax, colorbar=True, cmap='Oranges')
ax.set_title('Confusion Matrix - RoBERTa (Accuracy: 70%)',
             fontsize=12, fontweight='bold')
plt.tight_layout()
plt.savefig("cm_roberta.png", dpi=150, bbox_inches='tight')
plt.show()

"""## The Visualization of RoBERTa"""

# RoBERTa confirmed as the better model.
# apply it to the full dataset of 2,755 comments.

roberta_results = df['cleaned_text'].apply(get_roberta_sentiment)
df = pd.concat([df, roberta_results], axis=1)

df.to_csv("pokemon_sentiment.csv", index=False)
print("RoBERTa complete on full dataset!")
print(df['roberta_sentiment'].value_counts())
print(df['roberta_sentiment'].value_counts(normalize=True).mul(100).round(1))

#load dataset
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np
from wordcloud import WordCloud

df = pd.read_csv("pokemon_sentiment.csv")
colors = {'Positive': '#2ecc71', 'Neutral': '#95a5a6', 'Negative': '#e74c3c'}
counts = df['roberta_sentiment'].value_counts()

print(f"Total comments: {len(df)}")
print(counts)

#Figure 1 Bar chart

fig, ax = plt.subplots(figsize=(10, 6))
bars = ax.bar(counts.index,
              counts.values,
              color=[colors[s] for s in counts.index],
              edgecolor='white', linewidth=1.5)

ax.set_title("Overall Sentiment Distribution\n(Pokémon 30th Anniversary YouTube Comments)",
             fontsize=12,fontweight='bold')
ax.set_xlabel("Sentiment", fontsize=11)
ax.set_ylabel("Number of Comments", fontsize=11)
ax.spines['top'].set_visible(False)
ax.spines['right'].set_visible(False)

total = counts.sum()
for bar, count in zip(bars, counts.values):
    ax.text(bar.get_x() + bar.get_width()/2,
            bar.get_height() + 15,
            f'{count}\n({count/total*100:.1f}%)',
            ha='center', va='bottom', fontsize=11)

plt.tight_layout()
plt.savefig("roberta_overall.png", dpi=150, bbox_inches='tight')
plt.show()

#Figure 2 Pie Chart

fig, ax = plt.subplots(figsize=(10, 6))
wedges, texts, autotexts = ax.pie(
    counts.values,
    labels=counts.index,
    autopct='%1.1f%%',
    colors=[colors[s] for s in counts.index],
    startangle=90,
    pctdistance=0.85
)
for text in texts:
    text.set_fontsize(12)
for autotext in autotexts:
    autotext.set_fontsize(12)
    autotext.set_fontweight('bold')

ax.set_title("Sentiment Distribution\n(Pokémon 30th Anniversary YouTube Comments)",
             fontsize=12, fontweight='bold', pad=10)
plt.tight_layout()
plt.savefig("roberta_pie.png", dpi=150, bbox_inches='tight')
plt.show()

# Draw word cloud
from wordcloud import WordCloud, STOPWORDS

# Add stopwords to filter meaningless words
extra_stopwords = {'href', 'Im', 'lol', 'gonna', 'ZA', 'Pokmon','look','switch',
                   'will', 'one', 'got', 'still', 'back', 'now','game','games',
                   'really', 'much', 'even', 'way', 'thing', 'see', 'year',
                   'look', 'make', 'good', 'better', 'time','Pokemon',
                   'actually', 'first', 'go', 'get', 'play', 'feel'}
stopwords = STOPWORDS.union(extra_stopwords)

title = {
    'Positive': '😊 Most Common Words in Positive Reactions',
    'Neutral': '😐 Most Common Words in Neutral Reactions',
    'Negative': '😞 Most Common Words in Negative Reactions'
}
cmap = {
    'Positive': 'Greens',
    'Neutral': 'Greys',
    'Negative': 'Reds'
}

for sentiment in ['Positive', 'Neutral', 'Negative']:
    subset_text = ' '.join(
        df[df['roberta_sentiment'] == sentiment]['cleaned_text'].fillna('')
    )

    wc = WordCloud(
        width=800, height=500,
        background_color='black',
        colormap=cmap[sentiment],
        max_words=50,
        stopwords=stopwords,
        min_font_size=10
    ).generate(subset_text)

    fig, ax = plt.subplots(figsize=(10, 6))
    ax.imshow(wc, interpolation='bilinear')
    ax.axis('off')
    ax.set_title(title[sentiment], fontsize=12, fontweight='bold', pad=15)
    plt.tight_layout()
    plt.savefig(f"roberta_wordcloud_{sentiment.lower()}.png",
                dpi=150, bbox_inches='tight')
    plt.show()

# Draw word cloud
from wordcloud import WordCloud, STOPWORDS
import matplotlib.pyplot as plt

# Add stopwords to filter meaningless words
extra_stopwords = {'href', 'Im', 'lol', 'gonna', 'ZA', 'Pokmon','look','switch',
                   'will', 'one', 'got', 'still', 'back', 'now','game','games',
                   'really', 'much', 'even', 'way', 'thing', 'see', 'year',
                   'look', 'make', 'good', 'better', 'time','Pokemon',
                   'actually', 'first', 'go', 'get', 'play', 'feel'}
stopwords = STOPWORDS.union(extra_stopwords)

cmap = {'Positive': 'Greens', 'Neutral': 'Greys', 'Negative': 'Reds'}
title = {
    'Positive': '😊 Positive Comments',
    'Neutral':  '😐 Neutral Comments',
    'Negative': '😞 Negative Comments'
}

fig, axes = plt.subplots(1, 3, figsize=(18, 6))

for ax, sentiment in zip(axes, ['Positive', 'Neutral', 'Negative']):
    subset_text = ' '.join(
        df[df['roberta_sentiment'] == sentiment]['cleaned_text'].fillna('')
    )
    wc = WordCloud(
        width=600, height=400,
        background_color='black',
        colormap=cmap[sentiment],
        max_words=50,
        stopwords=stopwords,
        min_font_size=10
    ).generate(subset_text)
    ax.imshow(wc, interpolation='bilinear')
    ax.axis('off')
    ax.set_title(title[sentiment], fontsize=13, fontweight='bold', pad=10)

plt.suptitle("Most Common Words by Sentiment\n(Pokémon 30th Anniversary YouTube Comments)",
             fontsize=14, fontweight='bold', y=1.02)
plt.tight_layout()
plt.savefig("roberta_wordclouds_combined.png", dpi=150, bbox_inches='tight')
plt.show()